root = "."
tmp_dir = "tmp"

[build]
cmd = "swag init -g ./cmd/server/main.go --output ./docs --parseDependency --parseInternal --parseDepth 4 --exclude ./tmp,./docs,./vendor && go build -o tmp/main ./cmd/server"
bin = "tmp/main"

include_ext = ["go","mod","sum","yaml","yml","toml","env"]
exclude_dir  = ["tmp","docs","vendor",".git"]

[watcher]
ignore_dirs = ["tmp","docs","vendor",".git"]

